//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpustakaanAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anggota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anggota()
        {
            this.peminjaman = new HashSet<peminjaman>();
        }
    
        public int id_anggota { get; set; }
        public string nama_anggota { get; set; }
        public string alamat { get; set; }
        public string telp { get; set; }
        public Nullable<System.DateTime> tanggal_daftar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peminjaman> peminjaman { get; set; }
    }
}
