//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpustakaanAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buku()
        {
            this.peminjaman = new HashSet<peminjaman>();
        }
    
        public int id_buku { get; set; }
        public Nullable<int> id_kategori { get; set; }
        public string kode_buku { get; set; }
        public string judul_buku { get; set; }
        public string penulis { get; set; }
        public Nullable<int> stok { get; set; }
    
        public virtual kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peminjaman> peminjaman { get; set; }
    }
}
