//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpustakaanAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peminjaman
    {
        public int id_pinjam { get; set; }
        public int id_anggota { get; set; }
        public int id_user { get; set; }
        public int id_buku { get; set; }
        public System.DateTime tanggal_pinjam { get; set; }
        public Nullable<System.DateTime> tanggal_kembali { get; set; }
        public string status { get; set; }
    
        public virtual anggota anggota { get; set; }
        public virtual users users { get; set; }
        public virtual buku buku { get; set; }
    }
}
