//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpustakaanAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerpustakaanDBEntities : DbContext
    {
        public PerpustakaanDBEntities()
            : base("name=PerpustakaanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anggota> anggota { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<peminjaman> peminjaman { get; set; }
        public virtual DbSet<buku> buku { get; set; }
    }
}
